import { Place } from '../../types';
import { countries } from '../countries';

const regions = {
  cornwall: Place.from('Cornwall', countries.uk),
  cotswolds: Place.from('Cotswolds', countries.uk),
  devon: Place.from('Devon', countries.uk),
  kent: Place.from('Kent', countries.uk),
  lakes: Place.from('Lake District', countries.uk),
  lancashire: Place.from('Lancashire', countries.uk),
  midlands: Place.from('Midlands', countries.uk),
  norfolk: Place.from('Norfolk', countries.uk),
  northumberland: Place.from('Northumberland', countries.uk),
  scotland: Place.from('Scotland', countries.uk),
  sussex: Place.from('Sussex', countries.uk),
  wales: Place.from('Wales', countries.uk),
  warwickshire: Place.from('Warwickshire', countries.uk),
  yorkshire: Place.from('Yorkshire', countries.uk),
};

const municipalities = {
  barmouth: Place.from('Barmouth', regions.wales),
  bath: Place.from('Bath', countries.uk),
  berkhamsted: Place.from('Berkhamsted', countries.uk),
  bournemouth: Place.from('Bournemouth', countries.uk),
  brighton: Place.from('Brighton', countries.uk),
  bristol: Place.from('Bristol', countries.uk),
  canterbury: Place.from('Canterbury', regions.kent),
  carbisBay: Place.from('Carbis Bay', regions.cornwall),
  cheshunt: Place.from('Cheshunt', countries.uk),
  christchurch: Place.from('Christchurch', countries.uk),
  durham: Place.from('Durham', countries.uk),
  edinburgh: Place.from('Edinburgh', regions.scotland),
  falmouth: Place.from('Falmouth', regions.cornwall),
  folkestone: Place.from('Folkestone', regions.kent),
  foulridge: Place.from('Foulridge', regions.lancashire),
  greatYarmouth: Place.from('Great Yarmouth', regions.norfolk),
  hebdenBridge: Place.from('Hebden Bridge', regions.yorkshire),
  hemelHempstead: Place.from('Hemel Hempstead', countries.uk),
  hexham: Place.from('Hexham', regions.northumberland),
  huddersfield: Place.from('Huddersfield', regions.yorkshire),
  leightonBuzzard: Place.from('Leighton Buzzard', countries.uk),
  london: Place.from('London', countries.uk),
  manchester: Place.from('Manchester', countries.uk),
  mawganPorth: Place.from('Mawgan Porth', regions.cornwall),
  mousehole: Place.from('Mousehole', regions.cornwall),
  newquay: Place.from('Newquay', regions.cornwall),
  okehampton: Place.from('Okehampton', regions.devon),
  penzance: Place.from('Penzance', regions.cornwall),
  pontcysyllte: Place.from('Pontcysyllte', regions.wales),
  poole: Place.from('Poole', countries.uk),
  rye: Place.from('Rye', regions.sussex),
  skipton: Place.from('Skipton', regions.yorkshire),
  sowerbyBridge: Place.from('Sowerby Bridge', regions.yorkshire),
  standedgeTunnel: Place.from('Standedge Tunnel', countries.uk),
  stIves: Place.from('St Ives', regions.cornwall),
  stMawes: Place.from('St Mawes', regions.cornwall),
  stratfordUponAvon: Place.from('Stratford-upon-Avon', regions.midlands),
  ticehurst: Place.from('Ticehurst', regions.sussex),
  todmorden: Place.from('Todmorden', regions.yorkshire),
  warwick: Place.from('Warwick', regions.midlands),
  whitchurch: Place.from('Whitchurch', countries.uk),
  windermere: Place.from('Windermere', regions.lakes),
};

const accomodations = {
  artistResidencePenzance: Place.from(
    'Artist Residence',
    municipalities.penzance,
  ),
  birch: Place.from('Birch', municipalities.cheshunt),
  butlinsMinehead: Place.from('Butlins Minehead', regions.cornwall),
  chelseaHouseFalmouth: Place.from('Chelsea House', municipalities.falmouth),
  countyHotelHexham: Place.from('County Hotel', municipalities.hexham),
  curtainHotel: Place.from('The Curtain', municipalities.london),
  fallenAngel: Place.from('Fallen Angel', municipalities.mousehole),
  gannetInn: Place.from('Gannet Inn', municipalities.carbisBay),
  harbourHotelBristol: Place.from('Harbour Hotel', municipalities.bristol),
  hotelDuVinPoole: Place.from('Hotel du Vin', municipalities.poole),
  humbleBee: Place.from('Humble Bee', municipalities.okehampton),
  seahamHallHotel: Place.from('Seaham Hall Hotel', municipalities.durham),
  scarletHotel: Place.from('Scarlet Hotel', municipalities.mawganPorth),
  sedgefordHall: Place.from('Sedgeford Hall', regions.norfolk),
  starAndGarterFalmouth: Place.from('Star and Garter', municipalities.falmouth),
  thymeHotel: Place.from('Thyme Hotel', regions.cotswolds),
  velvetHotel: Place.from('Velvet Hotel', municipalities.manchester),
};

export const placesUk = {
  ...regions,
  ...municipalities,
  ...accomodations,
};
